# Nordic Baka Kitty - Full Miku/Teto/Neru Integration
foreground #bec8d1
background #2e3440

selection_foreground #2e3440
selection_background #bec8d1
cursor #bec8d1
cursor_text_color #2e3440

# Bordes y Tabs
active_border_color #bec8d1
inactive_border_color #3b4252
tab_bar_style powerline
active_tab_foreground   #2e3440
active_tab_background   #ffd543
inactive_tab_foreground #bec8d1
inactive_tab_background #854462

# --- Terminal Colors ---

# Black (Nord)
color0 #3b4252
color8 #4c566a

# Red (Teto)
color1 #d46a83
color9 #d46a83

# Green (Miku Verde)
color2  #52c7ad
color10 #52c7ad

# Yellow (Neru)
color3  #ffd543
color11 #ffd543

# Blue (Ahora Miku Azul Verdoso)
color4  #52c7ad
color12 #52c7ad

# Magenta (Teto Morado)
color5  #854462
color13 #854462

# Cyan (Miku Cian Principal)
color6  #86cecb
color14 #86cecb

# White (Ahora Miku Gris)
color7  #bec8d1
color15 #bec8d1

