include ./keybidings.conf
include ./colors.conf

# Font
font_family jetbrains-mono
italic_font auto
bold_italic_font auto
font_size 14.0

allow-remote-control   yes
font_size 22
enabled_layouts tall, stack, grid
draw_minimal_borders yes
window_padding_width 2
